name: Trigger Spur Webhook on Push or Button Click 🔔!

on:
  push:
    branches:
      - ext/spur/github
  workflow_dispatch:

jobs:
  trigger_webhook:
    runs-on: ubuntu-latest

    steps:
      - name: 📡 Curl Request to Trigger TestSuites on Spur
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -H "SPUR_GITHUB_KEY: U2FsdGVkX1+PzC34RJttgknR1o0ebwLgkmi+Zae478P5+SruRAiacPPzUMRJmPJS" \
          -H "sha: ${{ github.sha }}" \
          -H "repo: ${{ github.repository }}" \
          -H "override_url: " \
          "https://spurserverstagingep-aaeth2ftbteyhqed.z01.azurefd.net/api/integrations/github/webhook" \
          -o response.txt -w "%{http_code}" > status.txt 2>&1 &
          CURL_PID=$!
          timeout=2400
          elapsed=0
          while kill -0 $CURL_PID 2>/dev/null; do
            if [ $elapsed -ge $timeout ]; then
              echo "Webhook trigger is still running after 40 minutes. Continuing..."
              break
            fi
            sleep 60
            elapsed=$((elapsed+60))
            minutes=$((elapsed / 60))
            echo "Still waiting for response... (${minutes} minutes elapsed)"
            
            if [ -s response.txt ]; then
              echo "Response received. Checking status..."
              break
            fi
          done
          if [ -s status.txt ]; then
            STATUS=$(cat status.txt)
            if [ "$STATUS" = "200" ]; then
              echo "Webhook triggered successfully!"
            else
              echo "Webhook trigger status: $STATUS"
            fi
            cat response.txt
          else
            echo "Webhook trigger is still running. Check logs for final status."
          fi
          # Always exit successfully
          exit 0

# 🎈 Happy testing with Spur! 🎈
